### ISSUE TITLE
Add support for pass through args for lwc-jest

### ISSUE THREAD

**Issue by rcurry-sf** [muenzpraeger/lwc-create-app#53] opened 2019-06-11 18:52 UTC
**What is missing from the application? Please describe.**
It currently is not possible to update jest snapshots from the lwc-services test command.

**Describe the solution you'd like**
I was thinking about adding an `--updateSnapshot` option to lwc-create-app/blob/master/packages/lwc-services/src/commands/test.ts

**Describe alternatives you've considered**
An alternative to adding a specific command line option for updating the snapshots, would simply be support for argument passthrough.

**Additional context**
https://platformcloud.slack.com/archives/C5W3E40TC/p1560276843141400

**Comment by muenzpraeger** [comment] 2019-06-11 19:07
Yeah, I as looking into passthrough. The issue is that it‘s not possible with the underlying `Oclif` architecture. 

The alternative would be on allow _anything_ as flag (without built-in validation). Which I think in the mid-term is unavoidable.

Thoughts?

**Comment by rcurry-sf** [comment] 2019-06-12 06:42
Not sure I've followed the process here (in which case I apologize). I think there is an issue in master that is independent of the PR I've created.

**Comment by muenzpraeger** [comment] 2019-06-12 07:14
Released with 1.2.2 today

**Closed by muenzpraeger** 2019-06-12 07:14 UTC
